Repository betagouv/preuve-covoiturage, pull requests merged in 2019-09, with the labels that each got.

#254 Add Splashscreen
  dashboard/src/app/app-routing.module.ts
  dashboard/src/app/core/components/destroy-observable.ts
  dashboard/src/app/core/components/not-found/not-found.component.html
  dashboard/src/app/core/components/not-found/not-found.component.scss
  dashboard/src/app/core/components/not-found/not-found.component.ts
  dashboard/src/app/core/const/main.const.ts
  dashboard/src/app/core/core.module.ts
  dashboard/src/app/core/services/authentication/authentication.service.ts
  dashboard/src/app/modules/administration/pages/api/api.component.ts
  dashboard/src/app/modules/authentication/layouts/change-auth-layout/change-auth-layout.component.html
  dashboard/src/app/modules/authentication/layouts/change-auth-layout/change-auth-layout.component.scss
  dashboard/src/app/modules/authentication/layouts/change-auth-layout/change-auth-layout.component.ts
  dashboard/src/app/modules/authentication/pages/confirm-email/confirm-email.component.ts
  dashboard/src/app/modules/authentication/pages/invite-email/invite-email.component.ts
  dashboard/src/app/modules/stat/modules/stat-ui/components/stat-territory-view/stat-territory-view.component.ts
  dashboard/src/app/modules/trip/pages/trip-import/trip-import.component.ts
  dashboard/src/app/shared/components/footer/footer.component.html
  dashboard/src/app/shared/components/footer/footer.component.ts
  dashboard/src/app/shared/components/header/header.component.scss
  dashboard/src/assets/img/404.svg
  dashboard/src/assets/img/forgotten_password.svg
  dashboard/src/assets/img/rpc.svg
  dashboard/src/index.html
Labels: ✨ Enhancement, 📐 FRONT

#266 Correction du filtrage par AOMs et Opérateurs, création de la ro…
  api/config/aom.yml
  api/config/operators.yml
  api/config/registry.yml
  api/services/organization/transports/aomhttp.js
  api/services/organization/transports/operatorhttp.js
  dashboard/src/app/modules/aom/modules/ui/components/multipleDropdown/component.ts
  dashboard/src/app/modules/aom/services/aomService.ts
  dashboard/src/app/modules/journeys/components/filter/filter.component.ts
  dashboard/src/app/modules/journeys/components/filter/template.html
  dashboard/src/app/modules/journeys/services/journeyService.ts
  dashboard/src/app/modules/operator/modules/operators/ui/components/multipleDropdown/component.ts
  dashboard/src/app/modules/operator/services/operatorService.ts
Labels: 🐛 BUG, 📐 FRONT, 🔧 BACK

#269 retirer l'envoie d'email d'invitation sur la production
  api/services/user/entities/models/user.js
Labels: 🔧 BACK
