Repository betagouv/preuve-covoiturage, pull requests merged in 2019-11, with the labels that each got.

#510 Ajout des tests pour les templates
  dashboard/cypress/integration/e2e.ts
  dashboard/cypress/integration/integration.ts
  dashboard/cypress/support/apiValues/expectedTemplates.ts
  dashboard/cypress/support/apiValues/expectedTerritory.ts
  dashboard/cypress/support/reusables/auth/cypress_login.ts
  dashboard/cypress/support/reusables/auth/cypress_logout.ts
  dashboard/cypress/support/reusables/campaign/cypress_campaign_create.ts
  dashboard/cypress/support/reusables/campaign/cypress_campaign_create_from_template.ts
  dashboard/cypress/support/reusables/campaign/cypress_campaign_edit.ts
  dashboard/cypress/support/reusables/campaign/cypress_campaign_edit_created_from_template.ts
  dashboard/cypress/support/reusables/campaign/cypress_campaign_launch.ts
  dashboard/cypress/support/reusables/campaign/steps/campaign-create-first-step.ts
  dashboard/cypress/support/reusables/campaign/steps/campaign-create-fourth-step.ts
  dashboard/cypress/support/reusables/filter/cypress_filter.ts
  dashboard/cypress/support/reusables/notification.cypress.ts
  dashboard/cypress/support/reusables/operator/application.cypress.ts
  dashboard/cypress/support/reusables/operator/cypress_operator.ts
  dashboard/cypress/support/reusables/profile/cypress_profile.ts
  dashboard/cypress/support/reusables/territory/cypress_territory.ts
  dashboard/cypress/support/stories/operator.e2e.story.ts
  dashboard/cypress/support/stories/registry.e2e.story.ts
  dashboard/cypress/support/stories/territory.e2e.story.ts
  dashboard/cypress/support/stories/territory.story.ts
  dashboard/cypress/support/stubs/campaign/campaign-template.list.ts
  dashboard/src/app/modules/campaign/components/campaign-form/campaign-form.component.ts
  dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.ts
Labels: FRONT, sprint backlog

#516 Gestion des erreur HTTP + retour erreur email non valide
  dashboard/src/app/core/operators/catchHttpStatus.ts
  dashboard/src/app/core/services/api/json-rpc.service.ts
  dashboard/src/app/core/services/authentication/authentication.service.ts
  dashboard/src/app/modules/authentication/pages/forgotten-password/forgotten-password.component.ts
Labels: BUG, FRONT, staging backlog

#556 Back/migrations
  api/Procfile
  api/db/migrations/common/003_seed_role_table.up.sql
  api/db/migrations/operator/001_create_operator_table.up.sql
  api/package.json
  api/proxy/src/HttpTransport.ts
  api/services/acquisition/src/ServiceProvider.ts
  api/services/acquisition/src/commands/MigrateDataCommand.ts
  api/services/application/src/ServiceProvider.ts
  api/services/application/src/commands/MigrateDataCommand.ts
  api/services/application/src/helpers/setOwner.ts
  api/services/operator/package.json
  api/services/operator/src/ServiceProvider.ts
  api/services/operator/src/commands/MigrateDataCommand.ts
  api/services/user/src/ServiceProvider.ts
  api/services/user/src/commands/FixPermissionsCommand.ts
  api/services/user/src/commands/MigrateDataCommand.ts
  api/services/user/src/commands/SetPermissionsCommand.ts
  api/services/user/src/config/permissions.ts
  api/shared/application/find.schema.ts
  api/shared/application/list.schema.ts
  api/shared/application/revoke.schema.ts
  docker-compose.yml
Labels: BACK, sprint backlog

#560 mapid command
  api/db/migrations/territory/001_create_territory_table.up.sql
  api/proxy/package.json
  api/proxy/src/Kernel.ts
  api/proxy/src/commands/InseeSeedCommand.ts
  api/proxy/src/commands/MapIdCommand.ts
  api/services/acquisition/src/actions/LogAction.ts
  api/services/acquisition/src/commands/MigrateDataCommand.ts
  api/services/application/src/commands/MigrateDataCommand.ts
  api/services/operator/src/commands/MigrateDataCommand.ts
  api/services/territory/package.json
  api/services/territory/src/ServiceProvider.ts
  api/services/territory/src/commands/MigrateDataCommand.ts
  api/services/trip/src/commands/MigrateDataCommand.ts
Labels: BACK, sprint backlog

#555 Remise en place des restrictions dans le formulaire de création de campagne
  dashboard/cypress/support/apiValues/expectedCampaign.ts
  dashboard/cypress/support/reusables/campaign/cypress_campaign_create.ts
  dashboard/cypress/support/reusables/campaign/cypress_campaign_edit.ts
  dashboard/cypress/support/reusables/campaign/steps/campaign-create-third-step.ts
  dashboard/src/app/core/enums/campaign/restrictions.enum.ts
  dashboard/src/app/core/interfaces/campaign/api-format/campaign-global-rules.interface.ts
  dashboard/src/app/core/interfaces/campaign/ux-format/campaign-ux.interface.ts
  dashboard/src/app/modules/campaign/components/campaign-form/step-2/filters-form/filters-form.component.html
  dashboard/src/app/modules/campaign/components/campaign-form/step-3/restriction-form/restriction-form.component.html
  dashboard/src/app/modules/campaign/components/campaign-form/step-3/restriction-form/restriction-form.component.ts
  dashboard/src/app/modules/campaign/components/campaign-form/step-3/step-3-form/parameters-form.component.html
  dashboard/src/app/modules/campaign/components/campaign-form/step-3/step-3-form/parameters-form.component.ts
  dashboard/src/app/modules/campaign/services/campaign-formating.service.ts
Labels: FRONT, sprint backlog

#569 Grammaire, filtre communes et affichage utilisateur connecté dans tableau
  dashboard/cypress/support/reusables/campaign/steps/campaign-create-second-step.ts
  dashboard/src/app/modules/administration/pages/all-users/all-users.component.ts
  dashboard/src/app/modules/administration/pages/users/users.component.ts
  dashboard/src/app/modules/campaign/components/campaign-form/campaign-form.component.ts
  dashboard/src/app/modules/campaign/components/campaign-form/step-2/filters-form/filters-form.component.html
  dashboard/src/app/modules/filter/components/towns-autocomplete/towns-autocomplete.component.ts
  dashboard/src/app/modules/filter/services/town.service.ts
  dashboard/src/app/modules/stat/modules/stat-ui/components/stat-graph/stat-graph.component.html
  dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.html
  dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.ts
Labels: FRONT, sprint backlog

#562 Corrections des statistiques de covoiturage - prod
  api/services/trip/src/providers/TripPgRepositoryProvider.ts
  dashboard/src/app/modules/stat/services/stat-format.service.ts
Labels: BACK, BUG, FRONT, stats

#584 Lien invitation
  api/services/user/src/providers/UserNotificationProvider.ts
Labels: BACK

#586 Front/siret company api
  api/proxy/package.json
  api/proxy/src/Kernel.ts
  api/yarn.lock
  dashboard/cypress/support/apiValues/expectedOperator.ts
  dashboard/src/app/app.module.ts
  dashboard/src/app/core/entities/operator/operator.ts
  dashboard/src/app/core/entities/shared/company.ts
  dashboard/src/app/core/entities/territory/territory.ts
  dashboard/src/app/modules/campaign/components/campaign-map/campaign-map.component.ts
  dashboard/src/app/modules/company/company.module.ts
  dashboard/src/app/modules/company/services/company.service.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-form/operator-form.component.ts
  dashboard/src/app/modules/operator/services/operator.service.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
  dashboard/src/app/shared/modules/form/components/form-company/form-company.component.html
  dashboard/src/app/shared/modules/form/forms/form-company.ts
Labels: FRONT, staging backlog

#589 Front/op te crud fixes
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-details/operator-details.component.html
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-form/operator-form.component.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-details/territory-details.component.html
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
Labels: BUG, FRONT

#590 Conversion du typage des id de string > number
  dashboard/src/app/core/entities/IModel.ts
  dashboard/src/app/core/entities/authentication/user.ts
  dashboard/src/app/core/entities/campaign/api-format/campaign.ts
  dashboard/src/app/core/entities/campaign/incentive-formula-parameter.ts
  dashboard/src/app/core/entities/campaign/ux-format/campaign-ux.ts
  dashboard/src/app/core/entities/filter/filter.ts
  dashboard/src/app/core/entities/operator/operator.ts
  dashboard/src/app/core/entities/territory/territory.ts
  dashboard/src/app/core/entities/trip/person.ts
  dashboard/src/app/core/entities/trip/trip.ts
  dashboard/src/app/core/interfaces/campaign/api-format/campaignInterface.ts
  dashboard/src/app/core/interfaces/campaign/campaign-name.interface.ts
  dashboard/src/app/core/interfaces/campaign/ux-format/campaign-ux.interface.ts
  dashboard/src/app/core/interfaces/filter/filterInterface.ts
  dashboard/src/app/core/interfaces/operator/applicationInterface.ts
  dashboard/src/app/core/interfaces/operator/operatorInterface.ts
  dashboard/src/app/core/interfaces/territory/territoryInterface.ts
  dashboard/src/app/core/interfaces/trip/tripInterface.ts
  dashboard/src/app/core/interfaces/user/profileInterface.ts
  dashboard/src/app/core/services/api/api.service.ts
  dashboard/src/app/core/services/authentication/authentication.service.ts
  dashboard/src/app/core/services/common-data.service.ts
  dashboard/src/app/modules/administration/pages/users/users.component.ts
  dashboard/src/app/modules/campaign/components/campaign-card/campaign-card.component.ts
  dashboard/src/app/modules/campaign/components/campaign-form/campaign-form.component.ts
  dashboard/src/app/modules/campaign/services/campaign.service.ts
  dashboard/src/app/modules/company/services/company.service.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-autocomplete/operator-autocomplete.component.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-form/operator-form.component.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operators-autocomplete/operators-autocomplete.component.ts
  dashboard/src/app/modules/operator/services/application.service.ts
  dashboard/src/app/modules/operator/services/operator.service.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-autocomplete/territory-autocomplete.component.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
  dashboard/src/app/modules/territory/services/territory.service.ts
  dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.ts
Labels: FRONT, staging backlog

#594 Mise à jour des tests des templates
  dashboard/cypress/integration/integration.ts
  dashboard/cypress/support/apiValues/expectedTemplates.ts
  dashboard/cypress/support/reusables/campaign/cypress_campaign_create_from_template.ts
  dashboard/cypress/support/stories/territory.story.ts
  dashboard/cypress/support/stubs/campaign/campaign-template.list.ts
  dashboard/src/app/modules/campaign/services/campaign-formating.service.ts
  dashboard/src/app/modules/company/services/company.service.ts
Labels: FRONT

#592 Code owners
  .github/CODEOWNERS
  README.md
  api/.github/PULL_REQUEST_TEMPLATE/mobility-pass.md
Labels: BACK, DOC, FRONT

#595 Afficher en front le total calculé en back
  dashboard/src/app/core/interfaces/trip/tripInterface.ts
  dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.html
  dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.ts
  dashboard/src/app/modules/trip/services/trip.service.ts
Labels: FRONT, sprint backlog

#599 Feature: Identity
  api/db/migrations/20191119091826-identity.js
  api/db/migrations/carpool/20191119091826_create_carpool_identity_table.down.sql
  api/db/migrations/carpool/20191119091826_create_carpool_identity_table.up.sql
  api/package.json
  api/providers/crypto/package.json
  api/providers/geo/package.json
  api/providers/middleware/package.json
  api/providers/notification/package.json
  api/providers/sentry/package.json
  api/providers/token/package.json
  api/providers/validator/package.json
  api/proxy/package.json
  api/proxy/src/Kernel.ts
  api/proxy/src/commands/ProcessJourneyCommand.ts
  api/services/acquisition/package.json
  api/services/acquisition/src/ServiceProvider.ts
  api/services/acquisition/src/actions/CreateJourneyAction.ts
  api/services/acquisition/src/interfaces/JourneyRepositoryProviderInterface.ts
  api/services/acquisition/src/interfaces/index.ts
  api/services/acquisition/src/providers/JourneyPgRepositoryProvider.spec.ts
  api/services/acquisition/src/providers/JourneyPgRepositoryProvider.ts
  api/services/application/package.json
  api/services/company/package.json
  api/services/fraud/package.json
  api/services/normalization/package.json
  api/services/normalization/src/ServiceProvider.ts
  api/services/normalization/src/actions/NormalizationCostAction.ts
  api/services/normalization/src/actions/NormalizationGeoAction.ts
  api/services/normalization/src/actions/NormalizationRouteAction.ts
  api/services/normalization/src/actions/NormalizationTerritoryAction.ts
  api/services/normalization/src/config/connections.ts
  api/services/normalization/src/providers/TerritoryProvider.ts
  api/services/normalization/tests/territoryProvider.spec.ts
  api/services/operator/package.json
  api/services/policy/package.json
  api/services/territory/package.json
  api/services/trip/package.json
  api/services/trip/src/actions/CrosscheckAction.ts
  api/services/trip/src/interfaces/TripPgRepositoryProviderInterface.ts
  api/services/trip/src/providers/TripPgRepositoryProvider.ts
  api/services/user/package.json
  api/shared/acquisition/common/interfaces/AcquisitionInterface.ts
  api/shared/acquisition/create.contract.ts
  api/shared/common/interfaces/IdentityInterface.ts
  api/shared/common/interfaces/JourneyInterface.ts
  api/shared/common/interfaces/PersonInterface.ts
  api/shared/normalization/cost.contract.ts
  api/shared/normalization/geo.contract.ts
  api/shared/normalization/route.contract.ts
  api/shared/normalization/territory.contract.ts
  api/shared/trip/crosscheck.contract.ts
  api/yarn.lock
  dashboard/package-lock.json
  dashboard/package.json
Labels: BACK

#602 Erreur de meta manquante (pagination) dans les tests trip list
  dashboard/cypress/integration/integration.ts
  dashboard/cypress/support/stubs/trip/trip.list.ts
Labels: BUG, FRONT

#618 geo:fetch command
  api/proxy/src/Kernel.ts
  api/proxy/src/commands/GeoFetchCommand.ts
Labels: BACK, INFRA

#629 Page des statistiques publiques
  dashboard/cypress/fixtures/tmpPublicStats.json
  dashboard/cypress/integration/tmpPublicStats.ts
  dashboard/src/app/app-routing.module.ts
  dashboard/src/app/modules/stat/pages/temp-public-stats/temp-public-stats.component.html
  dashboard/src/app/modules/stat/pages/temp-public-stats/temp-public-stats.component.scss
  dashboard/src/app/modules/stat/pages/temp-public-stats/temp-public-stats.component.ts
  dashboard/src/app/modules/stat/services/stat-format.service.ts
  dashboard/src/app/modules/stat/services/stat-tmp-public.service.ts
  dashboard/src/app/modules/stat/stat-routing.module.ts
  dashboard/src/app/modules/stat/stat.module.ts
  dashboard/src/app/shared/components/header/header.component.html
  dashboard/src/app/shared/components/header/header.component.ts
Labels: FRONT

#623 Blocker lancement campagne, correction ux
  dashboard/cypress/support/stories/territory.story.ts
  dashboard/src/app/modules/campaign/pages/campaign-draft-view/campaign-draft-view.component.ts
  dashboard/src/app/modules/user/modules/profile-ui/components/profile-edition/profile-edition.component.html
Labels: FRONT, sprint backlog

#633 Cacher la statistique opérateur
  dashboard/src/app/modules/stat/config/stat.ts
Labels: FRONT
