Repository betagouv/preuve-covoiturage, pull requests merged in 2019-12, with the labels that each got.

#646 Fix/dev fixes
  api/db/migrations/trip/20191125100001_create_trip_view.up.sql
  api/services/trip/src/providers/TripRepositoryProvider.ts
  api/services/user/src/actions/MeUserAction.ts
  dashboard/src/app/core/entities/authentication/user.ts
  dashboard/src/app/modules/filter/services/filter.service.ts
Labels: BACK, BUG, FRONT

#652 Nettoyage des interfaces partagées
  api/db/migrations/trip/20191125100001_create_trip_view.up.sql
  api/services/user/src/interfaces/UserRepositoryProviderInterface.ts
  api/services/user/src/providers/UserPgRepositoryProvider.ts
  api/services/user/src/templates/confirm_email.hbs
  api/services/user/src/templates/email_changed.hbs
  api/services/user/src/templates/forgotten_password.hbs
  api/services/user/src/templates/invite.hbs
  api/shared/user/changePassword.contract.ts
  api/shared/user/common/interfaces/UserCreateInterface.ts
  api/shared/user/common/interfaces/UserFindInterface.ts
  api/shared/user/common/interfaces/UserFullInterface.ts
  api/shared/user/common/interfaces/UserInterface.ts
  api/shared/user/common/interfaces/UserListInterface.ts
  api/shared/user/common/interfaces/UserStatusInterface.ts
  api/shared/user/create.contract.ts
  api/shared/user/find.contract.ts
  dashboard/cypress/integration/integration.ts
  dashboard/cypress/support/expectedApiPayload/expectedFilter.ts
  dashboard/src/app/core/entities/api/jsonRPCParam.ts
  dashboard/src/app/core/entities/authentication/user.ts
  dashboard/src/app/core/services/authentication/authentication.service.ts
  dashboard/src/app/modules/administration/pages/all-users/all-users.component.ts
  dashboard/src/app/modules/administration/pages/users/users.component.ts
  dashboard/src/app/modules/authentication/pages/reset-forgotten-password/reset-forgotten-password.component.ts
  dashboard/src/app/modules/user/services/user-api.service.ts
  dashboard/src/app/modules/user/services/user-store.service.ts
Labels: BACK, Enhancement, FRONT

#657 Supprimer les redirections des erreurs de permissions en post vers login
  dashboard/src/app/core/services/api/json-rpc.service.ts
Labels: FRONT

#624 Changer les filtres pour les trajets & stats : villes >> insees
  api/services/trip/src/actions/ListAction.spec.ts
  api/services/trip/src/actions/StatsAction.spec.ts
  api/services/trip/src/providers/TripRepositoryProvider.ts
  api/shared/trip/common/interfaces/TripSearchInterface.ts
  api/shared/trip/common/schemas/search.ts
  dashboard/cypress/support/expectedApiPayload/expectedFilter.ts
  dashboard/cypress/support/reusables/filter/cypress_filter.ts
  dashboard/src/app/core/entities/filter/filter.ts
  dashboard/src/app/core/interfaces/filter/filterInterface.ts
  dashboard/src/app/core/interfaces/filter/filterUxInterface.ts
  dashboard/src/app/modules/campaign/campaign.module.ts
  dashboard/src/app/modules/campaign/components/campaign-form/step-2/campaign-insee-filter/campaign-insee-filter-start-end-form/campaign-insee-filter-start-end-form.component.scss
  dashboard/src/app/modules/filter/components/filter/filter.component.html
  dashboard/src/app/modules/filter/components/filter/filter.component.scss
  dashboard/src/app/modules/filter/components/filter/filter.component.ts
  dashboard/src/app/modules/filter/filter.module.ts
  dashboard/src/app/modules/filter/services/filter.service.ts
  dashboard/src/app/shared/modules/territory-to-insees-autocomplete/components/territories-to-insees-autocomplete/territories-to-insees-autocomplete.component.html
  dashboard/src/app/shared/modules/territory-to-insees-autocomplete/components/territories-to-insees-autocomplete/territories-to-insees-autocomplete.component.scss
  dashboard/src/app/shared/modules/territory-to-insees-autocomplete/components/territories-to-insees-autocomplete/territories-to-insees-autocomplete.component.ts
  dashboard/src/app/shared/modules/territory-to-insees-autocomplete/services/territory-to-insees-autocomplete.service.ts
  dashboard/src/app/shared/modules/territory-to-insees-autocomplete/territory-to-insees-autocomplete.module.ts
Labels: FRONT, sprint backlog

#672 Correction du "lazy-loading" des trajets
  dashboard/src/app/core/const/filter.const.ts
  dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.ts
Labels: BUG, FRONT, sprint backlog

#630 Tableau admin de suivis des campagnes
  api/services/policy/package.json
  api/services/policy/src/ServiceProvider.ts
  api/services/policy/src/actions/ListCampaignAction.ts
  api/services/policy/src/actions/ListCampaignTemplateAction.ts
  api/services/policy/src/interfaces/CampaignRepositoryProviderInterface.ts
  api/services/policy/src/providers/CampaignPgRepositoryProvider.ts
  api/services/policy/tests/CampaignService.spec.ts
  api/shared/policy/list.contract.ts
  api/shared/policy/list.schema.ts
  api/shared/policy/listTemplate.contract.ts
  dashboard/cypress/integration/integration.ts
  dashboard/cypress/support/generators/campaigns.generator.ts
  dashboard/cypress/support/reusables/campaign/admin-campaign-list.cypress.ts
  dashboard/cypress/support/stories/registry.story.ts
  dashboard/cypress/support/stubs/campaign/campaign-template.list.ts
  dashboard/cypress/support/stubs/campaign/campaign.list.ts
  dashboard/src/app/core/enums/campaign/campaign-status.enum.ts
  dashboard/src/app/modules/campaign/campaign-routing.module.ts
  dashboard/src/app/modules/campaign/campaign.module.ts
  dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-auto-complete/campaign-auto-complete.component.ts
  dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaigns-list/campaigns-list.component.html
  dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaigns-list/campaigns-list.component.ts
  dashboard/src/app/modules/campaign/pages/campaign-admin-list/campaign-admin-list.component.html
  dashboard/src/app/modules/campaign/pages/campaign-admin-list/campaign-admin-list.component.scss
  dashboard/src/app/modules/campaign/pages/campaign-admin-list/campaign-admin-list.component.ts
  dashboard/src/app/modules/campaign/pages/campaign-dashboard/campaign-dashboard.component.html
  dashboard/src/app/modules/campaign/pages/campaign-dashboard/campaign-dashboard.component.ts
  dashboard/src/app/modules/campaign/services/campaign.service.ts
  dashboard/src/app/shared/components/header/header.component.html
  dashboard/src/app/shared/components/header/header.component.ts
  dashboard/src/app/shared/components/list-item/list-item.component.scss
Labels: FRONT, sprint backlog

#636 Ajouter noms des opérateurs & territoires sur la liste des utilisateurs
  dashboard/src/app/core/components/dialog/confirm-dialog.component.ts
  dashboard/src/app/core/services/dialog.service.ts
  dashboard/src/app/modules/administration/pages/all-users/all-users.component.html
  dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaigns-list/campaigns-list.component.ts
  dashboard/src/app/modules/operator/modules/application-ui/components/application/application.component.ts
  dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.html
  dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.scss
  dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.ts
Labels: FRONT

#665 Ajouter l'action de suppression d'un opérateur dans l'interface admin
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-list/operator-list.component.html
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-list/operator-list.component.ts
Labels: FRONT, sprint backlog

#675 Correctif invitation + email double
  api/services/user/src/ServiceProvider.ts
  api/services/user/src/providers/UserPgRepositoryProvider.ts
Labels: BUG, FRONT, staging backlog

#686 Correction de la requête pour l'export
  api/services/trip/src/providers/TripRepositoryProvider.ts
Labels: BACK, BUG

#682 Fixer le problème de casting sur les statistiques (distance en s…
  api/services/trip/src/providers/TripRepositoryProvider.ts
  dashboard/src/app/core/interfaces/stat/StatInterface.ts
  dashboard/src/app/modules/stat/config/stat.ts
  dashboard/src/app/modules/stat/modules/stat-ui/components/stat-number/stat-number.component.html
  dashboard/src/app/modules/stat/pages/public-stat/public-stat.component.html
  dashboard/src/app/modules/stat/pages/public-stat/public-stat.component.ts
  dashboard/src/app/modules/stat/services/stat-format.service.ts
Labels: BACK, FRONT, sprint backlog

#694 Fix operator territory visibility filtering
  api/providers/notification/src/Notification.ts
  api/providers/notification/src/mail/MailjetDriver.ts
  api/proxy/src/HttpTransport.ts
  api/services/territory/src/actions/ListTerritoryOperatorAction.ts
Labels: BACK, FRONT, sprint backlog

#710 Carroyage de l'export
  api/db/migrations/20191210215209-recreate_trip_export.js
  api/db/migrations/trip/20191125100001_create_export_view.up.sql
  api/proxy/src/HttpTransport.ts
  api/proxy/src/middlewares/serverTokenMiddleware.ts
  api/services/application/src/providers/ApplicationPgRepositoryProvider.ts
  api/services/application/tests/ApplicationPgRepositoryProvider.spec.ts
  api/services/application/tests/ApplicationService.spec.ts
  api/shared/application/find.contract.ts
  api/shared/application/find.schema.ts
  api/shared/application/revoke.schema.ts
  dashboard/src/app/core/interfaces/operator/applicationInterface.ts
  dashboard/src/app/modules/operator/modules/application-ui/components/application/application.component.ts
  dashboard/src/app/modules/operator/services/application.service.ts
Labels: BACK

#711 Correction du message d'erreur lorsqu'un email a changé ou quand…
  dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.ts
Labels: BUG, FRONT

#720 Corrections UI
  dashboard/src/app/core/components/dialog/confirm-dialog.component.scss
  dashboard/src/app/core/components/dialog/confirm-dialog.component.ts
  dashboard/src/app/core/services/dialog.service.ts
  dashboard/src/app/modules/administration/pages/all-users/all-users.component.ts
  dashboard/src/app/modules/administration/pages/users/users.component.ts
  dashboard/src/app/modules/campaign/components/campaign-form/step-1/campaign-templates/campaign-templates.component.ts
  dashboard/src/app/modules/campaign/components/campaign-form/step-2/filters-form.component.html
  dashboard/src/app/modules/campaign/components/campaign-form/step-2/filters-form.component.scss
  dashboard/src/app/modules/campaign/components/campaign-form/step-2/filters-form.component.ts
  dashboard/src/app/modules/campaign/components/campaign-form/step-3/parameters-form.component.html
  dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaigns-list/campaigns-list.component.html
  dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaigns-list/campaigns-list.component.ts
  dashboard/src/app/modules/campaign/services/campaign-ui.service.ts
  dashboard/src/app/modules/filter/components/filter/filter.component.html
  dashboard/src/app/modules/filter/components/filter/filter.component.ts
  dashboard/src/app/modules/operator/modules/application-ui/components/application/application.component.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-list-view/operator-list-view.component.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-list/operator-list.component.html
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-list/operator-list.component.scss
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-list/operator-list.component.ts
  dashboard/src/app/modules/operator/modules/operator-visibility/components/operator-visibility-tree/operator-visibility-tree.component.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-list-view/territory-list-view.component.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-list/territory-list.component.html
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-list/territory-list.component.scss
  dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.ts
  dashboard/src/app/modules/trip/pages/trip-export/trip-export.component.html
  dashboard/src/app/modules/trip/pages/trip-export/trip-export.component.ts
  dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.html
  dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.ts
  dashboard/src/app/modules/user/modules/ui-user/components/users-list/users-list.component.ts
  dashboard/src/app/shared/modules/territory-to-insees-autocomplete/components/territories-to-insees-autocomplete/territories-to-insees-autocomplete.component.html
Labels: FRONT

#735 Variable d'environnement Docker
  .circleci/debug.sh
  api/.env.example
  docker-compose.yml
  docker/dashboard/Dockerfile
Labels: INFRA

#715 Améliorer les filtres sur les périodes en prenant en compte les…
  dashboard/cypress/support/expectedApiPayload/expectedCampaign.ts
  dashboard/cypress/support/expectedApiPayload/expectedFilter.ts
  dashboard/cypress/support/reusables/filter/cypress_filter.ts
  dashboard/cypress/support/reusables/user/users.cypress.ts
  dashboard/src/app/modules/campaign/services/campaign-formating.service.ts
  dashboard/src/app/modules/filter/services/filter.service.ts
  dashboard/src/app/modules/stat/services/stat-filtered.service.ts
  dashboard/src/app/modules/trip/pages/trip-export/trip-export.component.ts
  dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.ts
  dashboard/src/app/modules/trip/services/trip.service.ts
Labels: FRONT

#750 add acquisition:logerror action
  api/db/migrations/20191217111323-create-errors-table.js
  api/db/migrations/acquisition/20191217111323_create_errors_table.down.sql
  api/db/migrations/acquisition/20191217111323_create_errors_table.up.sql
  api/proxy/src/HttpTransport.ts
  api/proxy/src/middlewares/serverTokenMiddleware.ts
  api/services/acquisition/src/ServiceProvider.ts
  api/services/acquisition/src/actions/CreateJourneyAction.ts
  api/services/acquisition/src/actions/CreateJourneyLegacyAction.ts
  api/services/acquisition/src/actions/LogAction.ts
  api/services/acquisition/src/actions/LogErrorAction.ts
  api/services/acquisition/src/interfaces/ErrorRepositoryProviderInterface.ts
  api/services/acquisition/src/providers/ErrorPgRepositoryProvider.ts
  api/shared/acquisition/common/interfaces/AcquisitionErrorInterface.ts
  api/shared/acquisition/logerror.contract.ts
  api/shared/acquisition/logerror.schema.ts
Labels: BACK

#755 Correctif template email id
  api/services/user/src/actions/NotifyUserAction.ts
  api/services/user/src/providers/UserNotificationProvider.ts
Labels: BACK, BUG

#753 Service Company <> Territoire / Opérateur
  api/services/operator/src/providers/OperatorPgRepositoryProvider.ts
  api/services/territory/src/providers/TerritoryPgRepositoryProvider.ts
  api/services/user/src/actions/CreateUserAction.ts
  api/services/user/src/providers/UserPgRepositoryProvider.ts
  dashboard/src/app/core/entities/operator/operator.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
  dashboard/src/app/modules/territory/services/territory-api.service.ts
Labels: BACK, BUG, FRONT

#749 Refacto applications
  api/shared/application/common/interfaces/ApplicationCreateResultInterface.ts
  api/shared/application/common/interfaces/ApplicationInterface.ts
  api/shared/application/create.contract.ts
  api/shared/application/find.contract.ts
  api/shared/application/list.contract.ts
  api/shared/application/revoke.contract.ts
  dashboard/src/app/core/entities/operator/application.ts
  dashboard/src/app/core/services/store/crud-store.ts
  dashboard/src/app/modules/operator/modules/application-ui/components/application-form/application-form.component.ts
  dashboard/src/app/modules/operator/modules/application-ui/components/application/application.component.html
  dashboard/src/app/modules/operator/modules/application-ui/components/application/application.component.ts
  dashboard/src/app/modules/operator/services/application-api.service.ts
  dashboard/src/app/modules/operator/services/application-store.service.ts
  dashboard/src/app/modules/operator/services/application.service.ts
Labels: FRONT

#764 Correctif problème du formulaire opérateur / banque
  dashboard/src/app/core/const/validators.const.ts
  dashboard/src/app/core/entities/operator/operator.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-form/operator-form.component.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.html
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
  dashboard/src/app/shared/modules/form/components/form-bank/form-bank.component.html
  dashboard/src/app/shared/modules/form/forms/form-bank.ts
  dashboard/src/app/shared/modules/form/validators/bic.validator.ts
  dashboard/src/app/shared/modules/form/validators/iban.validator.ts
Labels: BUG, FRONT

#770 Template d'email pour l'export des trips
  api/.env.example
  api/services/trip/src/actions/BuildExportAction.ts
  api/services/trip/src/config/email.ts
  api/services/trip/src/config/notification.ts
  api/services/user/src/config/email.ts
Labels: BACK
