Repository betagouv/preuve-covoiturage, pull requests merged in 2019-10, with the labels that each got.

#352 Gestion utilisateurs pour les admins aom & territoires
  dashboard/src/app/modules/administration/administration-layout/administration-layout.component.ts
  dashboard/src/app/modules/administration/pages/users/users.component.html
  dashboard/src/app/modules/administration/pages/users/users.component.ts
  dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.html
  dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.ts
Labels: 📐 FRONT

#356 Corriger la vue des stats et des trajets côté opérateurs
  api/services/trip/src/actions/ListAction.ts
  api/services/trip/src/actions/StatsAction.ts
  api/services/user/src/config/permissions.ts
  dashboard/src/app/modules/stat/services/stat.service.ts
  dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.ts
  dashboard/src/app/modules/trip/pages/trip-stats/trip-stats.component.html
  dashboard/src/app/modules/trip/services/trip.service.ts
Labels: BACK, FRONT

#377 WIP Gestion des permissions
  api/providers/schema/src/models/user/schemas/userPatchSchema.ts
  api/services/application/src/actions/RevokeApplicationAction.ts
  api/services/application/src/interfaces/ApplicationRepositoryProviderInterface.ts
  api/services/application/src/providers/ApplicationRepositoryProvider.ts
  api/services/application/tests/ApplicationService.spec.ts
  netlify.toml
Labels: BACK, FRONT, sprint backlog

#379 Front : Centralisation des données redondantes
  api/services/user/src/config/permissions.ts
  api/yarn.lock
  dashboard/src/app/app.component.ts
  dashboard/src/app/core/entities/api/jsonRPCError.ts
  dashboard/src/app/core/services/api/api.service.ts
  dashboard/src/app/core/services/api/json-rpc.service.ts
  dashboard/src/app/core/services/authentication/authentication.service.ts
  dashboard/src/app/core/services/common-data.service.ts
  dashboard/src/app/modules/administration/pages/territory/territory.component.html
  dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-auto-complete/campaign-auto-complete.component.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-autocomplete/operator-autocomplete.component.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operators-autocomplete/operators-autocomplete.component.ts
  dashboard/src/app/modules/operator/services/operator.service.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territories-autocomplete/territories-autocomplete.component.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-autocomplete/territory-autocomplete.component.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-view/territory-view.component.ts
  dashboard/src/app/modules/user/modules/profile-ui/components/profile-edition/profile-edition.component.ts
  dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.ts
  dashboard/src/app/modules/user/services/user.service.ts
Labels: FRONT, sprint backlog

#351 Feat/263 osrm calc
  api/providers/geo/src/GeoProvider.ts
  api/providers/geo/src/interfaces/GeoProviderInterface.ts
  api/providers/geo/src/interfaces/PointInterface.ts
  api/providers/geo/src/providers/fr.gouv.beta.covoiturage.osrm.ts
  api/providers/geo/src/providers/index.ts
  api/providers/geo/src/providers/org.project-osrm.map.ts
  api/providers/token/src/TokenProvider.ts
  api/providers/token/src/interfaces/TokenProviderInterfaceResolver.ts
  api/proxy/src/HttpTransport.ts
  api/proxy/src/Kernel.ts
  api/proxy/src/config/jwt.ts
  api/proxy/tests/acquisitionPipeline.spec.ts
  api/services/application/src/ServiceProvider.ts
  api/services/normalization/src/ServiceProvider.ts
  api/services/normalization/src/actions/NormalizationRouteAction.ts
  api/services/normalization/src/config/workflow.ts
  api/services/normalization/tests/route.spec.ts
  yarn.lock
Labels: BACK

#381 Feat/pgadmin
  api/services/trip/src/actions/ListAction.spec.ts
  api/services/trip/src/actions/ListAction.ts
  docker-compose.yml
  docker/pgadmin/Dockerfile
  docker/pgadmin/config_local.py
Labels: INFRA, product backlog

#390 add @pdc/service-user ilos fix-permissions command
  README.md
  api/Procfile
  api/package.json
  api/scalingo/postbuild.sh
  api/services/user/src/ServiceProvider.ts
  api/services/user/src/commands/FixPermissionsCommand.ts
Labels: BACK, INFRA, sprint backlog

#403 Formatage tableau des trajets
  api/services/trip/src/actions/ListAction.ts
  api/services/trip/src/providers/TripPgRepositoryProvider.ts
  dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.html
  dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.ts
Labels: FRONT

#385 Fix Front : Modal de token | Back : harmonisation de la validati…
  api/providers/schema/src/models/user/schemas/userCreateSchema.ts
  dashboard/src/app/modules/operator/modules/application-ui/components/application-modal/application-modal.component.scss
Labels: FRONT

#402 Formulaire simplifier : opérateur / territoire
  api/providers/schema/src/models/contacts/interfaces/ContactsInterface.ts
  api/providers/schema/src/models/contacts/schemas/contactsSchema.ts
  api/providers/schema/src/models/operator/schemas/index.ts
  api/providers/schema/src/models/operator/schemas/operatorCreateSchema.ts
  api/providers/schema/src/models/operator/schemas/operatorPatchContactsSchema.ts
  api/providers/schema/src/models/operator/schemas/operatorPatchSchema.ts
  api/providers/schema/src/models/territory/schemas/index.ts
  api/providers/schema/src/models/territory/schemas/territoryCreateSchema.ts
  api/providers/schema/src/models/territory/schemas/territoryPatchContactsSchema.ts
  api/providers/schema/src/models/territory/schemas/territoryPatchSchema.ts
  api/services/operator/src/ServiceProvider.ts
  api/services/operator/src/actions/PatchContactsOperatorAction.ts
  api/services/territory/src/ServiceProvider.ts
  api/services/territory/src/actions/PatchContactsTerritoryAction.ts
  api/services/user/src/actions/ListUserAction.ts
  api/services/user/src/config/permissions.ts
  dashboard/src/app/core/services/api/api.service.ts
  dashboard/src/app/modules/administration/pages/operator/operator.component.html
  dashboard/src/app/modules/administration/pages/territory/territory.component.html
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-details/operator-details.component.html
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-details/operator-details.component.scss
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-details/operator-details.component.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-form/operator-form.component.html
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-form/operator-form.component.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-view/operator-view.component.html
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-view/operator-view.component.ts
  dashboard/src/app/modules/operator/modules/operator-ui/operator-ui.module.ts
  dashboard/src/app/modules/operator/services/operator.service.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.html
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
  dashboard/src/app/modules/territory/services/territory.service.ts
  dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.html
  dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.ts
  dashboard/src/app/shared/modules/details/components/details-contact/details-contact.component.html
  dashboard/src/app/shared/modules/details/components/details-contact/details-contact.component.scss
  dashboard/src/app/shared/modules/details/components/details-contact/details-contact.component.ts
  dashboard/src/app/shared/modules/details/details.module.ts
Labels: FRONT

#410 front user admin hot fix
  api/services/user/src/actions/ListUserAction.ts
  dashboard/src/app/modules/administration/pages/all-users/all-users.component.html
  dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.html
  dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.ts
Labels: BUG, FRONT, staging backlog

#412 Correction des ids en double les paramètre JSON RPC
  dashboard/src/app/core/services/api/json-rpc.service.ts
Labels: BUG, FRONT

#413 Front/user front hot fix
  dashboard/src/app/core/services/common-data.service.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operators-autocomplete/operators-autocomplete.component.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territories-autocomplete/territories-autocomplete.component.ts
Labels: BUG, FRONT

#421 set response status in journeys/push
  api/proxy/src/HttpTransport.ts
Labels: BACK, sprint backlog

#416 Feat/383 v1 retrocompat
  api/nodemon.json
  api/package.json
  api/providers/schema/src/models/journey/schemas/index.ts
  api/providers/schema/src/models/journey/schemas/journeyCreateLegacySchema.ts
  api/providers/sentry/package.json
  api/proxy/package.json
  api/proxy/src/HttpTransport.ts
  api/services/acquisition/package.json
  api/services/acquisition/src/ServiceProvider.ts
  api/services/acquisition/src/actions/CreateJourneyLegacyAction.ts
  api/services/acquisition/src/helpers/mapLegacyToLatest.spec.ts
  api/services/acquisition/src/helpers/mapLegacyToLatest.ts
  api/services/application/package.json
  api/services/normalization/package.json
  api/services/operator/package.json
  api/services/policy/package.json
  api/services/territory/package.json
  api/services/trip/package.json
  api/services/user/package.json
  api/yarn.lock
Labels: BACK, sprint backlog

#432 Prise en compte de l'environnement sur cypress
  .circleci/config.yml
  dashboard/cypress.json
  dashboard/cypress/integration/territory-e2e.ts
  dashboard/cypress/support/generators/stats.generator.ts
  dashboard/package.json
  dashboard/src/app/core/entities/stat/calculatedStat.ts
  dashboard/src/app/core/interfaces/stat/calculatedStatInterface.ts
  dashboard/src/app/modules/campaign/components/campaign-form/step-2/filters-form/filters-form.component.html
  dashboard/src/app/modules/operator/modules/operator-ui/components/operators-autocomplete/operators-autocomplete.component.ts
Labels: FRONT

#428 fix proxy http status
  api/providers/schema/src/models/contacts/schemas/contactSchema.ts
  api/providers/schema/src/models/contacts/schemas/contactsSchema.ts
  api/providers/schema/src/models/operator/schemas/operatorCreateSchema.ts
  api/providers/schema/src/models/operator/schemas/operatorPatchContactsSchema.ts
  api/providers/schema/src/models/territory/schemas/territoryCreateSchema.ts
  api/providers/schema/src/models/territory/schemas/territoryPatchContactsSchema.ts
  api/proxy/src/HttpTransport.ts
  api/services/user/src/actions/CreateUserAction.ts
  api/services/user/src/actions/ForgottenPasswordUserAction.ts
  api/services/user/src/actions/PatchUserAction.ts
  api/services/user/src/actions/SendConfirmEmailUserAction.ts
Labels: BACK

#437 Correctif : dropdown operateur territoire (ordi margot)
  dashboard/src/app/core/services/authentication/authentication.service.ts
  dashboard/src/app/modules/administration/pages/territory/territory.component.ts
  dashboard/src/app/modules/campaign/pages/campaign-dashboard/campaign-dashboard.component.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-autocomplete/operator-autocomplete.component.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-details/operator-details.component.html
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-autocomplete/territory-autocomplete.component.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-details/territory-details.component.html
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-list-view/territory-list-view.component.ts
Labels: BUG, FRONT, staging backlog

#468 Correctif email en double
  dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.ts
  dashboard/src/app/modules/user/services/user.service.ts
Labels: BUG, FRONT, sprint backlog

#469 Possibilité d'éditer les utilisateurs pour les Opérateurs et Territoires
  dashboard/src/app/core/services/authentication/authentication.service.ts
  dashboard/src/app/modules/administration/pages/all-users/all-users.component.html
  dashboard/src/app/modules/administration/pages/all-users/all-users.component.ts
  dashboard/src/app/modules/administration/pages/users/users.component.html
  dashboard/src/app/modules/administration/pages/users/users.component.ts
Labels: FRONT, sprint backlog

#470 Limite par défaut + Correctifs utilisateur
  dashboard/src/app/core/services/api/api.service.ts
  dashboard/src/app/modules/user/services/user.service.ts
Labels: BUG, FRONT, sprint backlog

#462 Back/acquisition tests
  api/providers/schema/src/models/incentive/schemas/incentiveSchema.ts
  api/providers/schema/src/models/journey/schemas/journeyCreateSchema.ts
  api/providers/schema/src/models/person/schemas/driverSchema.ts
  api/providers/schema/src/models/person/schemas/passengerSchema.ts
  api/providers/schema/src/models/position/schemas/endSchema.ts
  api/providers/schema/src/models/position/schemas/index.ts
  api/providers/schema/src/models/position/schemas/startSchema.ts
  api/providers/schema/src/models/travelPass/schemas/travelPassSchema.ts
  api/providers/schema/src/models/trip/schemas/tripCrosscheckSchema.ts
  api/providers/schema/src/models/trip/schemas/tripSchema.ts
  api/services/acquisition/src/ServiceProvider.ts
  api/services/acquisition/src/actions/CreateJourneyAction.ts
  api/services/acquisition/src/actions/LogAction.ts
  api/services/acquisition/src/config/ajv.ts
  api/services/acquisition/tests/AcquisitionService.spec.ts
  api/services/acquisition/tests/helpers/callFactory.ts
  api/services/acquisition/tests/mocks/JourneyMock.ts
  api/services/acquisition/tests/mocks/test10MissingStartDate.ts
  api/services/acquisition/tests/mocks/test11MissingEndDate.ts
  api/services/acquisition/tests/mocks/test12MissingJourneyId.ts
  api/services/acquisition/tests/mocks/test13MissingOperatorJourneyId.ts
  api/services/acquisition/tests/mocks/test14JourneyTooOld.ts
  api/services/acquisition/tests/mocks/test15ContributionTooLow.ts
  api/services/acquisition/tests/mocks/test16RevenueTooLow..ts
  api/services/acquisition/tests/mocks/test17SeatsTooLow..ts
  api/services/acquisition/tests/mocks/test18WrongOperatorClass.ts
  api/services/acquisition/tests/mocks/test19WrongEmailFormat.ts
  api/services/acquisition/tests/mocks/test20WrongIncentiveSiret.ts
  api/services/acquisition/tests/mocks/test22WrongIncentiveIndex.ts
  api/services/acquisition/tests/mocks/test23WrongIncentiveAmount.ts
  api/services/acquisition/tests/mocks/test24WrongPaymentAmount.ts
  api/services/acquisition/tests/mocks/test25UnsupportedTravelPass.ts
  api/services/acquisition/tests/mocks/test26DuplicateJourneyId.ts
  api/services/acquisition/tests/mocks/test2MissingUserAuth.ts
  api/services/acquisition/tests/mocks/test3FailsOnWrongPermissions.ts
  api/services/acquisition/tests/mocks/test4FailsOnMethodNotFound.ts
  api/services/acquisition/tests/mocks/test5PassengerOnly.ts
  api/services/acquisition/tests/mocks/test6Nobody.ts
  api/services/acquisition/tests/mocks/test7DriverOnly.ts
  api/services/acquisition/tests/mocks/test8StartDateInTheFuture.ts
  api/services/acquisition/tests/mocks/test9StartAfterEnd.ts
  api/yarn.lock
  package.json
  yarn.lock
Labels: BACK, sprint backlog

#478 Correctif filtre de recherche
  dashboard/src/app/modules/administration/pages/all-users/all-users.component.ts
  dashboard/src/app/modules/administration/pages/users/users.component.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-list/operator-list.component.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-list/territory-list.component.ts
Labels: BUG, FRONT, staging backlog

#480 Corrections affichage statistique
  dashboard/cypress/support/generators/const/dates.const.ts
  dashboard/src/app/core/services/authentication/authentication.service.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-form/operator-form.component.ts
  dashboard/src/app/modules/stat/services/stat-format.service.ts
Labels: FRONT, sprint backlog

#484 Redirection vers la page d'accueil pour les utilisateurs connecté depuis la page login
  dashboard/cypress/integration/integration.ts
  dashboard/cypress/support/reusables/auth/cypress_login.ts
  dashboard/cypress/support/stories/operator.story.ts
  dashboard/cypress/support/stories/registry.story.ts
  dashboard/cypress/support/stories/territory.story.ts
  dashboard/cypress/support/stubs/user/user.me.ts
  dashboard/src/app/core/guards/login-guard.service.ts
  dashboard/src/app/modules/authentication/authentication-routing.module.ts
Labels: FRONT

#485 Fix des formulaires Opérateurs et Territoires
  api/providers/schema/src/models/company/interfaces/CompanyInterface.ts
  api/providers/schema/src/models/company/schemas/companySchema.ts
  api/providers/schema/src/models/operator/interfaces/UpdateOperatorParamsInterface.ts
  api/providers/schema/src/models/operator/interfaces/index.ts
  api/providers/schema/src/models/operator/schemas/index.ts
  api/providers/schema/src/models/operator/schemas/operatorUpdateSchema.ts
  api/providers/schema/src/models/territory/interfaces/TerritoryInterface.ts
  api/providers/schema/src/models/territory/interfaces/UpdateTerritoryParamsInterface.ts
  api/providers/schema/src/models/territory/interfaces/index.ts
  api/providers/schema/src/models/territory/schemas/index.ts
  api/providers/schema/src/models/territory/schemas/territoryCreateSchema.ts
  api/providers/schema/src/models/territory/schemas/territoryUpdateSchema.ts
  api/providers/validator/src/cast/ibanCast.ts
  api/providers/validator/src/formats/rnaCustomFormat.ts
  api/providers/validator/src/macros/ibanMacro.ts
  api/providers/validator/tests/ValidatorProvider.spec.ts
  api/providers/validator/tests/parts/rnaFormatTest.spec.ts
  api/rebuild.sh
  api/services/application/src/config/ajv.ts
  api/services/fraud/src/config/ajv.ts
  api/services/normalization/src/config/ajv.ts
  api/services/operator/src/ServiceProvider.ts
  api/services/operator/src/actions/UpdateOperatorAction.ts
  api/services/operator/src/config/ajv.ts
  api/services/policy/src/config/ajv.ts
  api/services/territory/src/ServiceProvider.ts
  api/services/territory/src/actions/UpdateTerritoryAction.ts
  api/services/territory/src/config/ajv.ts
  api/services/territory/src/entities/Territory.ts
  api/services/trip/src/config/ajv.ts
  api/services/user/src/config/ajv.ts
  dashboard/src/app/core/const/validators.const.ts
  dashboard/src/app/core/entities/operator/operator.ts
  dashboard/src/app/core/entities/shared/address.ts
  dashboard/src/app/core/entities/shared/bank.ts
  dashboard/src/app/core/entities/shared/cgu.ts
  dashboard/src/app/core/entities/shared/company.ts
  dashboard/src/app/core/entities/shared/contact.ts
  dashboard/src/app/core/entities/shared/contacts.ts
  dashboard/src/app/core/entities/territory/territory.ts
  dashboard/src/app/core/entities/utils.ts
  dashboard/src/app/core/services/api/api.service.ts
  dashboard/src/app/modules/campaign/components/campaign-map/campaign-map.component.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-details/operator-details.component.html
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-details/operator-details.component.ts
  dashboard/src/app/modules/operator/modules/operator-ui/components/operator-form/operator-form.component.ts
  dashboard/src/app/modules/operator/services/operator.service.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territories-autocomplete/territories-autocomplete.component.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-details/territory-details.component.html
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.html
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
  dashboard/src/app/modules/territory/services/territory.service.ts
  dashboard/src/app/shared/modules/form/components/form-company/form-company.component.html
  dashboard/src/app/shared/modules/form/components/form-company/form-company.component.scss
  dashboard/src/app/shared/modules/form/forms/form-company.ts
Labels: BACK, FRONT

#502 Front / Email : mise à jour des contenus et des templates
  api/providers/notification/README.md
  api/providers/notification/package.json
  api/providers/notification/src/Notification.ts
  api/providers/notification/src/NotificationExtension.ts
  api/providers/notification/src/common/MailDriverInterface.ts
  api/providers/notification/src/common/NotificationConfigurationType.ts
  api/providers/notification/src/common/NotificationInterface.ts
  api/providers/notification/src/common/index.ts
  api/providers/notification/src/index.ts
  api/providers/notification/src/mail/MailjetDriver.spec.ts
  api/providers/notification/src/mail/MailjetDriver.ts
  api/providers/notification/tsconfig.json
  api/providers/schema/src/models/user/interfaces/UserNotifyParamsInterface.ts
  api/proxy/package.json
  api/services/user/package.json
  api/services/user/src/ServiceProvider.ts
  api/services/user/src/actions/CreateUserAction.ts
  api/services/user/src/actions/ForgottenPasswordUserAction.ts
  api/services/user/src/actions/NotifyUserAction.ts
  api/services/user/src/actions/PatchUserAction.ts
  api/services/user/src/actions/SendConfirmEmailUserAction.ts
  api/services/user/src/config/notification.ts
  api/services/user/src/templates/confirm_email.hbs
  api/services/user/src/templates/email_changed.hbs
  api/services/user/src/templates/forgotten_password.hbs
  api/services/user/src/templates/invite.hbs
Labels: BACK, FRONT, sprint backlog

#509 Front : ré-envoi de l'invitation
  api/providers/schema/src/models/user/schemas/index.ts
  api/providers/schema/src/models/user/schemas/userSendInvitationEmailSchema.ts
  api/services/user/src/ServiceProvider.ts
  api/services/user/src/actions/SendInvitationEmailUserAction.ts
  api/services/user/src/actions/index.ts
  dashboard/src/app/core/services/authentication/authentication.service.ts
Labels: BACK, BUG, FRONT

#514 fix des autocompletes
  dashboard/src/app/modules/operator/modules/operator-ui/components/operators-autocomplete/operators-autocomplete.component.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territories-autocomplete/territories-autocomplete.component.ts
Labels: BUG, FRONT
