Repository betagouv/preuve-covoiturage, pull requests merged in 2020-01, with the labels that each got.

#780 message d'erreur on profile > changement de mot de passe
  dashboard/src/app/modules/authentication/modules/change-password/components/change-password/change-password.component.ts
  dashboard/src/app/modules/user/modules/profile-ui/components/profile-edition/profile-edition.component.ts
Labels: BUG, FRONT

#782 Clean service commondata et fix de l'autocomplete campagnes
  dashboard/src/app/core/services/common-data.service.ts
  dashboard/src/app/modules/campaign/modules/campaign-ui/components/campaign-auto-complete/campaign-auto-complete.component.ts
  dashboard/src/app/modules/campaign/services/campaign-api.service.ts
Labels: BUG, FRONT

#789 Cache des statistiques
  api/services/trip/src/config/cache.ts
  api/services/trip/src/providers/StatCacheRepositoryProvider.ts
Labels: BACK, BUG

#794 Possibilité de changer le rôle d'utilisateur
  api/services/user/src/actions/PatchUserAction.ts
  api/services/user/src/interfaces/UserRepositoryProviderInterface.ts
  api/services/user/src/providers/UserPgRepositoryProvider.ts
  api/shared/user/common/interfaces/UserPatchInterface.ts
  api/shared/user/patch.schema.ts
  dashboard/src/app/core/entities/authentication/user.ts
  dashboard/src/app/modules/user/modules/ui-user/components/create-edit-user-form/create-edit-user-form.component.html
Labels: BACK, FRONT, sprint backlog

#793 Mise en conformité du mode consultation
  api/services/user/src/config/permissions.ts
  dashboard/src/app/core/services/common-data.service.ts
  dashboard/src/app/modules/administration/administration-layout/administration-layout.component.ts
  dashboard/src/app/modules/administration/administration-routing.module.ts
  dashboard/src/app/modules/campaign/pages/campaign-dashboard/campaign-dashboard.component.html
  dashboard/src/app/modules/campaign/pages/campaign-dashboard/campaign-dashboard.component.ts
Labels: BACK, FRONT

#810 Correction formulaire opérateur
  dashboard/src/app/shared/modules/form/components/form-bank/form-bank.component.ts
  dashboard/src/app/shared/modules/form/forms/form-bank.ts
  dashboard/src/app/shared/modules/form/validators/bic.validator.ts
  dashboard/src/app/shared/modules/form/validators/iban.validator.ts
Labels: BUG, FRONT
