Repository betagouv/preuve-covoiturage, pull requests merged in 2021-06, with the labels that each got.

#1379 Suppression de la possibilité de créer/modifier un contour géographique
  api/services/territory/src/providers/TerritoryPgRepositoryProvider.ts
  dashboard/src/app/core/entities/territory/territory.ts
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.html
  dashboard/src/app/modules/territory/modules/territory-ui/components/territory-form/territory-form.component.ts
  shared/territory/common/schema.ts
Labels: BACK, FRONT

#1383 Activation des attestations en prod
  api/proxy/src/HttpTransport.ts
  dashboard/src/app/modules/certificate/certificate-layout/certificate-layout.component.html
  dashboard/src/app/modules/certificate/pages/check/check.component.ts
  dashboard/src/app/modules/certificate/services/certificate-api.service.ts
  doc/docs/.vuepress/config.js
  doc/docs/.vuepress/public/attestation-meta.png
  doc/docs/.vuepress/public/attestation-sans-meta.png
  doc/docs/.vuepress/public/attestations.png
  doc/docs/.vuepress/public/logo-rpc.png
  doc/docs/contribuer/api/README.md
  doc/docs/contribuer/api/licenses-list.md
  doc/docs/contribuer/api/providers/README.md
  doc/docs/contribuer/api/proxy.md
  doc/docs/contribuer/api/services/README.md
  doc/docs/contribuer/app/index.md
  doc/docs/contribuer/index.md
  doc/docs/contribuer/repo/index.md
  doc/docs/contribuer/repo/infra.md
  doc/docs/contribute/index.md
  doc/docs/index.md
  doc/docs/operateurs/generer-attestation.md
  doc/docs/operateurs/index.md
  doc/docs/operateurs/outils.md
  doc/docs/operateurs/preuves/acces.md
  doc/docs/operateurs/preuves/index.md
  doc/docs/operateurs/preuves/invalider.md
  doc/docs/operateurs/preuves/limites.md
  doc/docs/operateurs/preuves/schema.md
  doc/docs/operateurs/preuves/statut.md
  doc/docs/operateurs/visibilite-du-nom-de-loperateur.md
  doc/docs/partners/index.md
Labels: ATTESTATION, BACK, DOC

#1382 Mise à jour des liens de documentation
  dashboard/src/app/core/const/main.const.ts
  dashboard/src/app/modules/administration/pages/api/api.component.html
  dashboard/src/app/modules/administration/pages/api/api.component.ts
  dashboard/src/app/modules/stat/modules/stat-ui/components/stat-operator-view/stat-operator-view.component.html
  dashboard/src/app/modules/stat/modules/stat-ui/components/stat-operator-view/stat-operator-view.component.ts
  dashboard/src/app/modules/stat/modules/stat-ui/components/stat-territory-view/stat-territory-view.component.html
  dashboard/src/app/modules/stat/modules/stat-ui/components/stat-territory-view/stat-territory-view.component.ts
  dashboard/src/app/modules/stat/pages/public-stat/public-stat.component.html
  dashboard/src/app/modules/stat/pages/public-stat/public-stat.component.ts
  dashboard/src/app/modules/trip/pages/trip-import/trip-import.component.html
  dashboard/src/app/modules/trip/pages/trip-import/trip-import.component.ts
  dashboard/src/app/shared/components/footer/footer.component.html
  dashboard/src/app/shared/components/header/header.component.ts
Labels: FRONT

#1391 Namespace du docker-compose de test
  README.md
  docker-compose.yml
  docker/api/Dockerfile
  docker/dashboard/Dockerfile
  docker/dashboard/dev.env.js
  docker/lint/Dockerfile
  e2e.sh
Labels: INFRA

#1393 add test for wrong login
  dashboard/src/app/modules/authentication/pages/login/login.component.html
  tests/cypress/integration/UserLogin.feature
Labels: FRONT

#1392 MAJ doc des attestations
  doc/docs/contribuer/api/providers/crypto/index.md
  doc/docs/contribuer/api/providers/date/index.md
  doc/docs/contribuer/api/providers/file/index.md
  doc/docs/contribuer/api/providers/geo/index.md
  doc/docs/contribuer/api/providers/middleware/index.md
  doc/docs/contribuer/api/providers/notification/index.md
  doc/docs/contribuer/api/providers/pdfcert/index.md
  doc/docs/contribuer/api/providers/qrcode/index.md
  doc/docs/contribuer/api/providers/seed/index.md
  doc/docs/contribuer/api/providers/sentry/index.md
  doc/docs/contribuer/api/providers/template/index.md
  doc/docs/contribuer/api/providers/test/index.md
  doc/docs/contribuer/api/providers/token/index.md
  doc/docs/contribuer/api/providers/validator/index.md
  doc/docs/contribuer/api/services/acquisition/index.md
  doc/docs/contribuer/api/services/application/index.md
  doc/docs/contribuer/api/services/carpool/index.md
  doc/docs/contribuer/api/services/certificate/index.md
  doc/docs/contribuer/api/services/company/index.md
  doc/docs/contribuer/api/services/fraud/index.md
  doc/docs/contribuer/api/services/honor/index.md
  doc/docs/contribuer/api/services/monitoring/index.md
  doc/docs/contribuer/api/services/normalization/index.md
  doc/docs/contribuer/api/services/operator/index.md
  doc/docs/contribuer/api/services/policy/index.md
  doc/docs/contribuer/api/services/territory/index.md
  doc/docs/contribuer/api/services/trip/index.md
  doc/docs/contribuer/api/services/user/index.md
  doc/docs/operateurs/generer-attestation.md
  doc/gen/providers.js
  doc/gen/services.js
  doc/package.json
  doc/yarn.lock
Labels: DOC

#1400 Fix/1350 1
  dashboard/angular.json
  dashboard/src/app/core/types/stat/statDataNameType.ts
  dashboard/src/app/modules/stat/modules/stat-ui/components/stat-graph-base.ts
  dashboard/src/app/modules/stat/modules/stat-ui/components/stat-graph/stat-graph-carbon/stat-graph-carbon.component.html
  dashboard/src/app/modules/stat/modules/stat-ui/components/stat-graph/stat-graph-carpooler-vehicule/stat-graph-carpooler-vehicule.component.html
  dashboard/src/app/modules/stat/modules/stat-ui/components/stat-graph/stat-graph-carpoolers/stat-graph-carpoolers.component.html
  dashboard/src/app/modules/stat/modules/stat-ui/components/stat-graph/stat-graph-distance/stat-graph-distance.component.html
  dashboard/src/app/modules/stat/modules/stat-ui/components/stat-graph/stat-graph-petrol/stat-graph-petrol.component.html
  dashboard/src/app/modules/stat/modules/stat-ui/components/stat-graph/stat-graph-trip/stat-graph-trip.component.html
Labels: FRONT

#1409 Fix MJML
  api/providers/notification/package.json
  api/yarn.lock
Labels: BACK

#1408 Hotfix - création d'attestation
  api/services/carpool/src/providers/IdentityRepositoryProvider.ts
  shared/carpool/finduuid.schema.ts
  shared/certificate/create.schema.ts
  shared/common/schemas/findIdentity.ts
Labels: ATTESTATION, BACK

#1415 fix cert.create schema
  api/services/carpool/src/providers/IdentityRepositoryProvider.ts
  shared/carpool/finduuid.schema.ts
  shared/certificate/create.schema.ts
  shared/common/schemas/findIdentity.ts
Labels: ATTESTATION, BACK

#1406 Commandes géo
  api/db/migrations/20210618155305-territory_surface_bigint.js
  api/db/migrations/territory/20210618155305_bigint_surface.down.sql
  api/db/migrations/territory/20210618155305_bigint_surface.up.sql
  api/proxy/src/Kernel.ts
  api/proxy/src/commands/GeoFetchCommand.ts
  api/proxy/src/commands/MigrateInseeCommand.ts
  api/proxy/src/commands/SyncGeoShapeCommand.ts
  api/proxy/src/commands/SyncLegacyProductionCommand.ts
  api/proxy/src/commands/SyncSurfacePopulationCommand.ts
Labels: BACK
