Repository betagouv/preuve-covoiturage, pull requests merged in 2021-12, with the labels that each got.

#1594 Update/linter
  .github/workflows/analysis-dep.yml
  .github/workflows/analysis-linter.yml
  .github/workflows/analysis-test-e2e.yml
  .github/workflows/analysis-test-integration.yml
  .github/workflows/analysis-test-unit.yml
  .github/workflows/deploy-dashboard-production.yml
  .vscode/settings.json
  api/ilos/core/src/foundation/ServiceContainer.ts
  api/providers/notification/src/NotificationMailTransporter.ts
  api/providers/notification/src/interfaces/NotificationTransporterInterface.ts
  api/providers/qrcode/src/lib/QRCode.ts
  api/providers/test/src/fixtures/generators/TripGenerator.ts
  api/providers/test/src/fixtures/id_atlantis.ts
  api/providers/test/src/fixtures/id_olympus.ts
  api/providers/validator/src/keywords/castKeyword.ts
  api/proxy/src/HttpTransport.ts
  api/services/acquisition/src/providers/ErrorPgRepositoryProvider.ts
  api/services/certificate/src/actions/CreateCertificateAction.spec.ts
  api/services/fraud/src/interfaces/ProcessableCarpoolRepositoryProviderInterface.ts
  api/services/policy/src/actions/CreateCampaignAction.integration.spec.ts
  api/services/policy/src/actions/DeleteCampaignAction.integration.spec.ts
  api/services/policy/src/actions/LaunchCampaignAction.integration.spec.ts
  api/services/policy/src/actions/PatchCampaignAction.integration.spec.ts
  api/services/policy/src/engine/rules/AbstractStatefulRule.ts
  api/services/policy/src/engine/templates/macro.ts
  api/services/policy/src/middlewares/ValidateRuleParametersMiddleware.ts
  api/services/trip/src/commands/ReplayOpendataExportCommand.ts
  api/services/trip/src/providers/TripRepositoryProvider.ts
  api/services/user/src/providers/AuthRepositoryProvider.integration.spec.ts
  api/services/user/src/providers/UserPgRepositoryProvider.ts
  api/yarn.lock
  dashboard/src/app/core/entities/authentication/user.ts
  dashboard/src/app/core/entities/operator/application.ts
  dashboard/src/app/core/entities/territory/territory.ts
  dashboard/src/app/core/interfaces/campaign/api-format/campaign-global-rules.interface.ts
  dashboard/src/app/core/services/api/json-rpc.crud.ts
  dashboard/src/app/core/services/authentication/authentication.service.ts
  dashboard/src/app/core/services/store/crud-store.ts
  dashboard/src/app/core/services/store/getlist-store.ts
  dashboard/src/app/modules/campaign/components/campaign-form/step-3/parameters-form.component.ts
  dashboard/src/app/modules/user/services/user-api.service.ts
  docker/lint/package.json
  docker/lint/yarn.lock
Labels: BACK, INFRA, AMELIORATION

#1599 Update/angular-12
  dashboard/angular.json
  dashboard/package.json
  dashboard/src/polyfills.ts
  dashboard/src/styles/theme.scss
  dashboard/yarn.lock
Labels: FRONT

#1609 Trigger update de trajets
  README.md
  api/db/migrations/20211214213748-update-trip-listview.js
  api/db/migrations/trip/20211214213748_update_trip_listview.down.sql
  api/db/migrations/trip/20211214213748_update_trip_listview.up.sql
Labels: BUG, BACK, FRAUDE

#1620 fix: remove duplicate city response that could lead to wrong insee
  api/services/territory/src/providers/GeoRepositoryProvider.ts
  shared/territory/common/geo/GeoCodeTypeEnum.ts
Labels: BUG
