Repository betagouv/preuve-covoiturage, pull requests merged in 2021-11, with the labels that each got.

#1549 Création d'attestation vide
  .nvmrc
  api/services/certificate/src/actions/CreateCertificateAction.spec.ts
  api/services/certificate/src/actions/CreateCertificateAction.ts
Labels: BACK, ATTESTATION

#1547 Fix/opendata upload
  api/services/trip/package-lock.json
  api/services/trip/package.json
  api/services/trip/src/actions/BuildExportAction.ts
  api/services/trip/src/actions/PublishOpenDataAction.ts
  api/services/trip/src/actions/opendata/BuildResourceDescription.spec.ts
  api/services/trip/src/actions/opendata/BuildResourceDescription.ts
  api/services/trip/src/interfaces/DataGouvInterface.ts
  api/services/trip/src/interfaces/OpenDataContextMetadata.ts
  api/services/trip/src/providers/DataGouvProvider.ts
  api/services/trip/src/providers/TripRepositoryProvider.ts
  shared/trip/common/interfaces/TerritoryTripsInterface.ts
  shared/trip/publishOpenData.contract.ts
  shared/trip/publishOpenData.schema.ts
Labels: Open Data Automation

#1551 fix: remove production env check for apdf cron process
  api/services/trip/src/actions/ActiveCampaignExcelExportAction.spec.ts
  api/services/trip/src/actions/ActiveCampaignExcelExportAction.ts
Labels: Fund Calls Automation

#1558 Fix/opendata schema
  api/services/trip/src/actions/BuildExportAction.ts
  api/services/trip/src/actions/PublishOpenDataAction.ts
  api/services/trip/src/actions/PublishOpendataAction.spec.ts
  shared/trip/publishOpenData.schema.ts
Labels: BUG, Open Data Automation

#1552 fix Redis warnings
  api/ilos/connection-redis/src/RedisConnection.ts
  api/ilos/transport-redis/src/QueueTransport.ts
Labels: BACK, AMELIORATION

#1564 Distance et durée calculées
  api/services/acquisition/src/actions/LogRequestAction.ts
  shared/carpool/crosscheck.schema.ts
Labels: BUG, BACK

#1579 fix: fixed fields for opendata, remove unused
  api/services/trip/src/actions/BuildExportAction.ts
Labels: Open Data Automation, AMELIORATION

#1567 Fix incentive for trip list view
  api/services/trip/src/providers/TripRepositoryProvider.ts
  dashboard/src/app/core/services/store/getlist-store.ts
  dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.html
  dashboard/src/app/modules/trip/modules/ui-trip/components/trip-table/trip-table.component.ts
  dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.html
  dashboard/src/app/modules/trip/pages/trip-list/trip-list.component.ts
Labels: BUG, FRONT
