Repository betagouv/preuve-covoiturage, pull requests merged in 2023-02, with the labels that each got.

#1984 [frontend] création des attestations opérateur avec `operator_user_id` uniquement
  api/services/certificate/src/actions/CreateCertificateAction.spec.ts
  dashboard/src/app/modules/administration/pages/certificate-list/certificate-list.component.html
  dashboard/src/app/modules/administration/pages/certificate-list/certificate-list.component.ts
  dashboard/src/app/modules/certificate/services/certificate-api.service.ts
  shared/certificate/common/interfaces/IdentityIdentifiersInterface.ts
  shared/certificate/download.contract.ts
Labels: BUG, FRONT, ATTESTATION

#1903 feat: generate phone file tool
  shell.nix
  tools/README.md
  tools/phone.js
  tools/phone.sh
Labels: keep

#1996 [hotfix] Millesime APDF
  api/services/apdf/src/providers/APDFRepositoryProvider.ts
Labels: BUG, BACK, APDF

#2002 bump @betagouvpdc/evolution-geo to 1.2.4
  api/db/package.json
  api/yarn.lock
Labels: INFRA, AMELIORATION, Territoire
